
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class AdConfig : Luban.BeanBase
{
    public AdConfig(ByteBuf _buf) 
    {
        AdSlotId = _buf.ReadString();
        AdType = _buf.ReadString();
        TriggerScene = _buf.ReadString();
        MinLevelUnlock = _buf.ReadInt();
        if(_buf.ReadBool()){ RewardType = _buf.ReadString(); } else { RewardType = null; }
        if(_buf.ReadBool()){ RewardAmount = _buf.ReadInt(); } else { RewardAmount = null; }
        DailyLimit = _buf.ReadInt();
    }

    public static AdConfig DeserializeAdConfig(ByteBuf _buf)
    {
        return new cfg.AdConfig(_buf);
    }

    /// <summary>
    /// 广告位ID
    /// </summary>
    public readonly string AdSlotId;
    /// <summary>
    /// 广告类型
    /// </summary>
    public readonly string AdType;
    /// <summary>
    /// 触发场景
    /// </summary>
    public readonly string TriggerScene;
    /// <summary>
    /// 最低解锁关卡(延迟爆发)
    /// </summary>
    public readonly int MinLevelUnlock;
    /// <summary>
    /// 奖励类型
    /// </summary>
    public readonly string RewardType;
    /// <summary>
    /// 奖励数量
    /// </summary>
    public readonly int? RewardAmount;
    /// <summary>
    /// 每日观看上限(0=无限)
    /// </summary>
    public readonly int DailyLimit;
   
    public const int __ID__ = -1117086801;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "adSlotId:" + AdSlotId + ","
        + "adType:" + AdType + ","
        + "triggerScene:" + TriggerScene + ","
        + "minLevelUnlock:" + MinLevelUnlock + ","
        + "rewardType:" + RewardType + ","
        + "rewardAmount:" + RewardAmount + ","
        + "dailyLimit:" + DailyLimit + ","
        + "}";
    }
}
}

