
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class AntiAddictionConfig : Luban.BeanBase
{
    public AntiAddictionConfig(ByteBuf _buf) 
    {
        RuleId = _buf.ReadString();
        UserType = _buf.ReadString();
        MaxDailyMinutes = _buf.ReadInt();
        EyeCareInterval = _buf.ReadInt();
        EyeCareMessage = _buf.ReadString();
        ForceQuit = _buf.ReadBool();
    }

    public static AntiAddictionConfig DeserializeAntiAddictionConfig(ByteBuf _buf)
    {
        return new cfg.AntiAddictionConfig(_buf);
    }

    /// <summary>
    /// 规则ID
    /// </summary>
    public readonly string RuleId;
    /// <summary>
    /// 用户类型
    /// </summary>
    public readonly string UserType;
    /// <summary>
    /// 每日最大游戏时长(分钟0=无限制)
    /// </summary>
    public readonly int MaxDailyMinutes;
    /// <summary>
    /// 护眼提醒间隔(分钟)
    /// </summary>
    public readonly int EyeCareInterval;
    /// <summary>
    /// 提醒文案
    /// </summary>
    public readonly string EyeCareMessage;
    /// <summary>
    /// 是否强制退出
    /// </summary>
    public readonly bool ForceQuit;
   
    public const int __ID__ = 1849089733;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ruleId:" + RuleId + ","
        + "userType:" + UserType + ","
        + "maxDailyMinutes:" + MaxDailyMinutes + ","
        + "eyeCareInterval:" + EyeCareInterval + ","
        + "eyeCareMessage:" + EyeCareMessage + ","
        + "forceQuit:" + ForceQuit + ","
        + "}";
    }
}
}

