
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class AvatarEventItem : Luban.BeanBase
{
    public AvatarEventItem(ByteBuf _buf) 
    {
        AvatarEventId = _buf.ReadString();
        AvatarId = _buf.ReadString();
        AvatarName = _buf.ReadString();
        AvatarAsset = _buf.ReadString();
        SortOrder = _buf.ReadInt();
        DropWeight = _buf.ReadInt();
    }

    public static AvatarEventItem DeserializeAvatarEventItem(ByteBuf _buf)
    {
        return new cfg.AvatarEventItem(_buf);
    }

    /// <summary>
    /// 活动ID
    /// </summary>
    public readonly string AvatarEventId;
    /// <summary>
    /// 头像ID
    /// </summary>
    public readonly string AvatarId;
    /// <summary>
    /// 头像名称
    /// </summary>
    public readonly string AvatarName;
    /// <summary>
    /// 头像资源名
    /// </summary>
    public readonly string AvatarAsset;
    /// <summary>
    /// 展示排序(1-8)
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 碎片掉落权重
    /// </summary>
    public readonly int DropWeight;
   
    public const int __ID__ = 1297098186;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "avatarEventId:" + AvatarEventId + ","
        + "avatarId:" + AvatarId + ","
        + "avatarName:" + AvatarName + ","
        + "avatarAsset:" + AvatarAsset + ","
        + "sortOrder:" + SortOrder + ","
        + "dropWeight:" + DropWeight + ","
        + "}";
    }
}
}

