
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class AvatarEventConfig : Luban.BeanBase
{
    public AvatarEventConfig(ByteBuf _buf) 
    {
        AvatarEventId = _buf.ReadString();
        ThemeName = _buf.ReadString();
        StartTime = _buf.ReadString();
        EndTime = _buf.ReadString();
        TokensPerBox = _buf.ReadInt();
        FragmentsPerAvatar = _buf.ReadInt();
        TotalNormalAvatars = _buf.ReadInt();
        HasPremium = _buf.ReadBool();
        if(_buf.ReadBool()){ PremiumAvatarAsset = _buf.ReadString(); } else { PremiumAvatarAsset = null; }
        if(_buf.ReadBool()){ PremiumAvatarName = _buf.ReadString(); } else { PremiumAvatarName = null; }
    }

    public static AvatarEventConfig DeserializeAvatarEventConfig(ByteBuf _buf)
    {
        return new cfg.AvatarEventConfig(_buf);
    }

    /// <summary>
    /// 活动ID
    /// </summary>
    public readonly string AvatarEventId;
    /// <summary>
    /// 主题名称
    /// </summary>
    public readonly string ThemeName;
    /// <summary>
    /// 开始时间
    /// </summary>
    public readonly string StartTime;
    /// <summary>
    /// 结束时间
    /// </summary>
    public readonly string EndTime;
    /// <summary>
    /// 开箱消耗代币数
    /// </summary>
    public readonly int TokensPerBox;
    /// <summary>
    /// 合成需碎片数
    /// </summary>
    public readonly int FragmentsPerAvatar;
    /// <summary>
    /// 普通头像数量
    /// </summary>
    public readonly int TotalNormalAvatars;
    /// <summary>
    /// 有无Premium头像
    /// </summary>
    public readonly bool HasPremium;
    /// <summary>
    /// Premium头像资源名
    /// </summary>
    public readonly string PremiumAvatarAsset;
    /// <summary>
    /// Premium头像名称
    /// </summary>
    public readonly string PremiumAvatarName;
   
    public const int __ID__ = 794713145;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "avatarEventId:" + AvatarEventId + ","
        + "themeName:" + ThemeName + ","
        + "startTime:" + StartTime + ","
        + "endTime:" + EndTime + ","
        + "tokensPerBox:" + TokensPerBox + ","
        + "fragmentsPerAvatar:" + FragmentsPerAvatar + ","
        + "totalNormalAvatars:" + TotalNormalAvatars + ","
        + "hasPremium:" + HasPremium + ","
        + "premiumAvatarAsset:" + PremiumAvatarAsset + ","
        + "premiumAvatarName:" + PremiumAvatarName + ","
        + "}";
    }
}
}

