
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class BadgeConfig : Luban.BeanBase
{
    public BadgeConfig(ByteBuf _buf) 
    {
        BadgeLevel = _buf.ReadInt();
        TitleZh = _buf.ReadString();
        TitleEn = _buf.ReadString();
        Icon = _buf.ReadString();
        RequiredScore = _buf.ReadInt();
        RewardCoins = _buf.ReadInt();
        if(_buf.ReadBool()){ RewardItemId = _buf.ReadString(); } else { RewardItemId = null; }
        if(_buf.ReadBool()){ RewardItemCount = _buf.ReadInt(); } else { RewardItemCount = null; }
        if(_buf.ReadBool()){ RewardSpecial = _buf.ReadString(); } else { RewardSpecial = null; }
    }

    public static BadgeConfig DeserializeBadgeConfig(ByteBuf _buf)
    {
        return new cfg.BadgeConfig(_buf);
    }

    /// <summary>
    /// 等级(1-10)
    /// </summary>
    public readonly int BadgeLevel;
    /// <summary>
    /// 中文称号
    /// </summary>
    public readonly string TitleZh;
    /// <summary>
    /// 英文称号
    /// </summary>
    public readonly string TitleEn;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 所需学习积分
    /// </summary>
    public readonly int RequiredScore;
    /// <summary>
    /// 奖励金币
    /// </summary>
    public readonly int RewardCoins;
    /// <summary>
    /// 奖励道具ID
    /// </summary>
    public readonly string RewardItemId;
    /// <summary>
    /// 奖励道具数量
    /// </summary>
    public readonly int? RewardItemCount;
    /// <summary>
    /// 特殊奖励资源名
    /// </summary>
    public readonly string RewardSpecial;
   
    public const int __ID__ = 393473563;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "badgeLevel:" + BadgeLevel + ","
        + "titleZh:" + TitleZh + ","
        + "titleEn:" + TitleEn + ","
        + "icon:" + Icon + ","
        + "requiredScore:" + RequiredScore + ","
        + "rewardCoins:" + RewardCoins + ","
        + "rewardItemId:" + RewardItemId + ","
        + "rewardItemCount:" + RewardItemCount + ","
        + "rewardSpecial:" + RewardSpecial + ","
        + "}";
    }
}
}

