
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class CoinRule : Luban.BeanBase
{
    public CoinRule(ByteBuf _buf) 
    {
        RuleId = _buf.ReadString();
        RuleType = _buf.ReadString();
        Action = _buf.ReadString();
        Amount = _buf.ReadInt();
        Condition = _buf.ReadString();
        Version = _buf.ReadString();
    }

    public static CoinRule DeserializeCoinRule(ByteBuf _buf)
    {
        return new cfg.CoinRule(_buf);
    }

    /// <summary>
    /// 规则ID
    /// </summary>
    public readonly string RuleId;
    /// <summary>
    /// 类型(earn/spend)
    /// </summary>
    public readonly string RuleType;
    /// <summary>
    /// 触发行为
    /// </summary>
    public readonly string Action;
    /// <summary>
    /// 金币数量
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// 触发条件
    /// </summary>
    public readonly string Condition;
    /// <summary>
    /// 引入版本
    /// </summary>
    public readonly string Version;
   
    public const int __ID__ = 332337047;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ruleId:" + RuleId + ","
        + "ruleType:" + RuleType + ","
        + "action:" + Action + ","
        + "amount:" + Amount + ","
        + "condition:" + Condition + ","
        + "version:" + Version + ","
        + "}";
    }
}
}

