
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class DailyChallengeConfig : Luban.BeanBase
{
    public DailyChallengeConfig(ByteBuf _buf) 
    {
        ChallengeId = _buf.ReadString();
        ChallengeDate = _buf.ReadString();
        ChallengeType = _buf.ReadString();
        ContentEn = _buf.ReadString();
        ContentZh = _buf.ReadString();
        Source = _buf.ReadString();
        RewardCoins = _buf.ReadInt();
    }

    public static DailyChallengeConfig DeserializeDailyChallengeConfig(ByteBuf _buf)
    {
        return new cfg.DailyChallengeConfig(_buf);
    }

    /// <summary>
    /// 挑战ID
    /// </summary>
    public readonly string ChallengeId;
    /// <summary>
    /// 日期(YYYY-MM-DD)
    /// </summary>
    public readonly string ChallengeDate;
    /// <summary>
    /// 类型(sentence_fill/quote)
    /// </summary>
    public readonly string ChallengeType;
    /// <summary>
    /// 英文内容
    /// </summary>
    public readonly string ContentEn;
    /// <summary>
    /// 中文翻译
    /// </summary>
    public readonly string ContentZh;
    /// <summary>
    /// 来源
    /// </summary>
    public readonly string Source;
    /// <summary>
    /// 完成奖励金币
    /// </summary>
    public readonly int RewardCoins;
   
    public const int __ID__ = 280121750;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "challengeId:" + ChallengeId + ","
        + "challengeDate:" + ChallengeDate + ","
        + "challengeType:" + ChallengeType + ","
        + "contentEn:" + ContentEn + ","
        + "contentZh:" + ContentZh + ","
        + "source:" + Source + ","
        + "rewardCoins:" + RewardCoins + ","
        + "}";
    }
}
}

