
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class DailyRewardConfig : Luban.BeanBase
{
    public DailyRewardConfig(ByteBuf _buf) 
    {
        Day = _buf.ReadInt();
        RewardType = _buf.ReadString();
        if(_buf.ReadBool()){ RewardCoins = _buf.ReadInt(); } else { RewardCoins = null; }
        if(_buf.ReadBool()){ RewardItemId = _buf.ReadString(); } else { RewardItemId = null; }
        if(_buf.ReadBool()){ RewardItemCount = _buf.ReadInt(); } else { RewardItemCount = null; }
        IsMilestone = _buf.ReadBool();
    }

    public static DailyRewardConfig DeserializeDailyRewardConfig(ByteBuf _buf)
    {
        return new cfg.DailyRewardConfig(_buf);
    }

    /// <summary>
    /// 连续登录天数(1-15)
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 奖励类型
    /// </summary>
    public readonly string RewardType;
    /// <summary>
    /// 奖励金币数
    /// </summary>
    public readonly int? RewardCoins;
    /// <summary>
    /// 奖励道具ID
    /// </summary>
    public readonly string RewardItemId;
    /// <summary>
    /// 奖励道具数量
    /// </summary>
    public readonly int? RewardItemCount;
    /// <summary>
    /// 是否大奖节点
    /// </summary>
    public readonly bool IsMilestone;
   
    public const int __ID__ = 1465173216;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "day:" + Day + ","
        + "rewardType:" + RewardType + ","
        + "rewardCoins:" + RewardCoins + ","
        + "rewardItemId:" + RewardItemId + ","
        + "rewardItemCount:" + RewardItemCount + ","
        + "isMilestone:" + IsMilestone + ","
        + "}";
    }
}
}

