
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class EventConfig : Luban.BeanBase
{
    public EventConfig(ByteBuf _buf) 
    {
        EventId = _buf.ReadString();
        EventType = _buf.ReadString();
        EventName = _buf.ReadString();
        Recurrence = _buf.ReadString();
        DurationHours = _buf.ReadInt();
        NeedWordMark = _buf.ReadBool();
        if(_buf.ReadBool()){ MarkIcon = _buf.ReadString(); } else { MarkIcon = null; }
        if(_buf.ReadBool()){ MarkRatio = _buf.ReadFloat(); } else { MarkRatio = null; }
        if(_buf.ReadBool()){ MarkMin = _buf.ReadInt(); } else { MarkMin = null; }
        if(_buf.ReadBool()){ MarkMax = _buf.ReadInt(); } else { MarkMax = null; }
        if(_buf.ReadBool()){ RewardCurrency = _buf.ReadString(); } else { RewardCurrency = null; }
        if(_buf.ReadBool()){ RewardPerMark = _buf.ReadInt(); } else { RewardPerMark = null; }
        Version = _buf.ReadString();
    }

    public static EventConfig DeserializeEventConfig(ByteBuf _buf)
    {
        return new cfg.EventConfig(_buf);
    }

    /// <summary>
    /// 活动ID
    /// </summary>
    public readonly string EventId;
    /// <summary>
    /// 活动类型
    /// </summary>
    public readonly string EventType;
    /// <summary>
    /// 活动名称
    /// </summary>
    public readonly string EventName;
    /// <summary>
    /// 循环规则
    /// </summary>
    public readonly string Recurrence;
    /// <summary>
    /// 单期持续时长(小时)
    /// </summary>
    public readonly int DurationHours;
    /// <summary>
    /// 是否需要标记目标词
    /// </summary>
    public readonly bool NeedWordMark;
    /// <summary>
    /// 标记图标资源名
    /// </summary>
    public readonly string MarkIcon;
    /// <summary>
    /// 标记比例
    /// </summary>
    public readonly float? MarkRatio;
    /// <summary>
    /// 最少标记数
    /// </summary>
    public readonly int? MarkMin;
    /// <summary>
    /// 最多标记数
    /// </summary>
    public readonly int? MarkMax;
    /// <summary>
    /// 产出货币类型
    /// </summary>
    public readonly string RewardCurrency;
    /// <summary>
    /// 每个标记奖励数量
    /// </summary>
    public readonly int? RewardPerMark;
    /// <summary>
    /// 引入版本
    /// </summary>
    public readonly string Version;
   
    public const int __ID__ = 1695707090;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "eventId:" + EventId + ","
        + "eventType:" + EventType + ","
        + "eventName:" + EventName + ","
        + "recurrence:" + Recurrence + ","
        + "durationHours:" + DurationHours + ","
        + "needWordMark:" + NeedWordMark + ","
        + "markIcon:" + MarkIcon + ","
        + "markRatio:" + MarkRatio + ","
        + "markMin:" + MarkMin + ","
        + "markMax:" + MarkMax + ","
        + "rewardCurrency:" + RewardCurrency + ","
        + "rewardPerMark:" + RewardPerMark + ","
        + "version:" + Version + ","
        + "}";
    }
}
}

