
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        ItemId = _buf.ReadString();
        ItemName = _buf.ReadString();
        ItemNameZh = _buf.ReadString();
        SlotPosition = _buf.ReadInt();
        Icon = _buf.ReadString();
        PriceType = _buf.ReadString();
        PriceAmount = _buf.ReadInt();
        EffectType = _buf.ReadString();
        Description = _buf.ReadString();
        Version = _buf.ReadString();
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new cfg.ItemConfig(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly string ItemId;
    /// <summary>
    /// 道具英文名
    /// </summary>
    public readonly string ItemName;
    /// <summary>
    /// 道具中文名
    /// </summary>
    public readonly string ItemNameZh;
    /// <summary>
    /// 道具栏位置(1-6)
    /// </summary>
    public readonly int SlotPosition;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 价格类型
    /// </summary>
    public readonly string PriceType;
    /// <summary>
    /// 价格数量
    /// </summary>
    public readonly int PriceAmount;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly string EffectType;
    /// <summary>
    /// 功能描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 引入版本
    /// </summary>
    public readonly string Version;
   
    public const int __ID__ = 218178591;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "itemName:" + ItemName + ","
        + "itemNameZh:" + ItemNameZh + ","
        + "slotPosition:" + SlotPosition + ","
        + "icon:" + Icon + ","
        + "priceType:" + PriceType + ","
        + "priceAmount:" + PriceAmount + ","
        + "effectType:" + EffectType + ","
        + "description:" + Description + ","
        + "version:" + Version + ","
        + "}";
    }
}
}

