
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class LandmarkCardConfig : Luban.BeanBase
{
    public LandmarkCardConfig(ByteBuf _buf) 
    {
        CardId = _buf.ReadString();
        PackId = _buf.ReadString();
        NameZh = _buf.ReadString();
        NameEn = _buf.ReadString();
        Image = _buf.ReadString();
        DescriptionZh = _buf.ReadString();
        DescriptionEn = _buf.ReadString();
        FunFact = _buf.ReadString();
        UnlockAtLevel = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
    }

    public static LandmarkCardConfig DeserializeLandmarkCardConfig(ByteBuf _buf)
    {
        return new cfg.LandmarkCardConfig(_buf);
    }

    /// <summary>
    /// 卡片ID
    /// </summary>
    public readonly string CardId;
    /// <summary>
    /// 所属关卡包ID
    /// </summary>
    public readonly string PackId;
    /// <summary>
    /// 中文名
    /// </summary>
    public readonly string NameZh;
    /// <summary>
    /// 英文名
    /// </summary>
    public readonly string NameEn;
    /// <summary>
    /// 图片资源名
    /// </summary>
    public readonly string Image;
    /// <summary>
    /// 中文描述
    /// </summary>
    public readonly string DescriptionZh;
    /// <summary>
    /// 英文描述
    /// </summary>
    public readonly string DescriptionEn;
    /// <summary>
    /// 趣味知识
    /// </summary>
    public readonly string FunFact;
    /// <summary>
    /// 包内第几关解锁
    /// </summary>
    public readonly int UnlockAtLevel;
    /// <summary>
    /// 展示排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -650524236;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "cardId:" + CardId + ","
        + "packId:" + PackId + ","
        + "nameZh:" + NameZh + ","
        + "nameEn:" + NameEn + ","
        + "image:" + Image + ","
        + "descriptionZh:" + DescriptionZh + ","
        + "descriptionEn:" + DescriptionEn + ","
        + "funFact:" + FunFact + ","
        + "unlockAtLevel:" + UnlockAtLevel + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

