
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class PackConfig : Luban.BeanBase
{
    public PackConfig(ByteBuf _buf) 
    {
        PackId = _buf.ReadString();
        StageId = _buf.ReadString();
        ThemeEn = _buf.ReadString();
        ThemeZh = _buf.ReadString();
        TotalLevels = _buf.ReadInt();
        WordCount = _buf.ReadInt();
        SortOrder = _buf.ReadInt();
        UnlockType = _buf.ReadString();
        if(_buf.ReadBool()){ RequiredPackId = _buf.ReadString(); } else { RequiredPackId = null; }
        if(_buf.ReadBool()){ NextPackId = _buf.ReadString(); } else { NextPackId = null; }
    }

    public static PackConfig DeserializePackConfig(ByteBuf _buf)
    {
        return new cfg.PackConfig(_buf);
    }

    /// <summary>
    /// 关卡包ID
    /// </summary>
    public readonly string PackId;
    /// <summary>
    /// 所属学段ID
    /// </summary>
    public readonly string StageId;
    /// <summary>
    /// 主题英文名
    /// </summary>
    public readonly string ThemeEn;
    /// <summary>
    /// 主题中文名
    /// </summary>
    public readonly string ThemeZh;
    /// <summary>
    /// 总关卡数
    /// </summary>
    public readonly int TotalLevels;
    /// <summary>
    /// 包含单词数
    /// </summary>
    public readonly int WordCount;
    /// <summary>
    /// 学段内排序
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 解锁方式
    /// </summary>
    public readonly string UnlockType;
    /// <summary>
    /// 前置关卡包ID
    /// </summary>
    public readonly string RequiredPackId;
    /// <summary>
    /// 下一个关卡包ID
    /// </summary>
    public readonly string NextPackId;
   
    public const int __ID__ = -2141180251;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "packId:" + PackId + ","
        + "stageId:" + StageId + ","
        + "themeEn:" + ThemeEn + ","
        + "themeZh:" + ThemeZh + ","
        + "totalLevels:" + TotalLevels + ","
        + "wordCount:" + WordCount + ","
        + "sortOrder:" + SortOrder + ","
        + "unlockType:" + UnlockType + ","
        + "requiredPackId:" + RequiredPackId + ","
        + "nextPackId:" + NextPackId + ","
        + "}";
    }
}
}

