
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class ProvinceMilestoneConfig : Luban.BeanBase
{
    public ProvinceMilestoneConfig(ByteBuf _buf) 
    {
        MilestoneId = _buf.ReadString();
        TargetScore = _buf.ReadInt();
        RewardCoinsPerPlayer = _buf.ReadInt();
        MilestoneMessage = _buf.ReadString();
    }

    public static ProvinceMilestoneConfig DeserializeProvinceMilestoneConfig(ByteBuf _buf)
    {
        return new cfg.ProvinceMilestoneConfig(_buf);
    }

    /// <summary>
    /// 里程碑ID
    /// </summary>
    public readonly string MilestoneId;
    /// <summary>
    /// 目标累计学习积分
    /// </summary>
    public readonly int TargetScore;
    /// <summary>
    /// 每位玩家奖励金币
    /// </summary>
    public readonly int RewardCoinsPerPlayer;
    /// <summary>
    /// 达成提示文案
    /// </summary>
    public readonly string MilestoneMessage;
   
    public const int __ID__ = -575892520;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "milestoneId:" + MilestoneId + ","
        + "targetScore:" + TargetScore + ","
        + "rewardCoinsPerPlayer:" + RewardCoinsPerPlayer + ","
        + "milestoneMessage:" + MilestoneMessage + ","
        + "}";
    }
}
}

