
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class SeasonConfig : Luban.BeanBase
{
    public SeasonConfig(ByteBuf _buf) 
    {
        SeasonId = _buf.ReadString();
        SeasonName = _buf.ReadString();
        StartDate = _buf.ReadString();
        EndDate = _buf.ReadString();
    }

    public static SeasonConfig DeserializeSeasonConfig(ByteBuf _buf)
    {
        return new cfg.SeasonConfig(_buf);
    }

    /// <summary>
    /// 赛季ID
    /// </summary>
    public readonly string SeasonId;
    /// <summary>
    /// 赛季名称
    /// </summary>
    public readonly string SeasonName;
    /// <summary>
    /// 开始日期
    /// </summary>
    public readonly string StartDate;
    /// <summary>
    /// 结束日期
    /// </summary>
    public readonly string EndDate;
   
    public const int __ID__ = 1781900655;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "seasonId:" + SeasonId + ","
        + "seasonName:" + SeasonName + ","
        + "startDate:" + StartDate + ","
        + "endDate:" + EndDate + ","
        + "}";
    }
}
}

