
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class SeasonCrownConfig : Luban.BeanBase
{
    public SeasonCrownConfig(ByteBuf _buf) 
    {
        SeasonId = _buf.ReadString();
        NodeIndex = _buf.ReadInt();
        RequiredPoints = _buf.ReadInt();
        CrownAsset = _buf.ReadString();
        CrownName = _buf.ReadString();
    }

    public static SeasonCrownConfig DeserializeSeasonCrownConfig(ByteBuf _buf)
    {
        return new cfg.SeasonCrownConfig(_buf);
    }

    /// <summary>
    /// 赛季ID
    /// </summary>
    public readonly string SeasonId;
    /// <summary>
    /// 节点序号(1/2)
    /// </summary>
    public readonly int NodeIndex;
    /// <summary>
    /// 所需Crown Points
    /// </summary>
    public readonly int RequiredPoints;
    /// <summary>
    /// 皇冠资源名
    /// </summary>
    public readonly string CrownAsset;
    /// <summary>
    /// 皇冠名称
    /// </summary>
    public readonly string CrownName;
   
    public const int __ID__ = 610833612;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "seasonId:" + SeasonId + ","
        + "nodeIndex:" + NodeIndex + ","
        + "requiredPoints:" + RequiredPoints + ","
        + "crownAsset:" + CrownAsset + ","
        + "crownName:" + CrownName + ","
        + "}";
    }
}
}

