
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class SeasonFrameConfig : Luban.BeanBase
{
    public SeasonFrameConfig(ByteBuf _buf) 
    {
        SeasonId = _buf.ReadString();
        NodeIndex = _buf.ReadInt();
        RequiredPoints = _buf.ReadInt();
        FrameAsset = _buf.ReadString();
        FrameName = _buf.ReadString();
    }

    public static SeasonFrameConfig DeserializeSeasonFrameConfig(ByteBuf _buf)
    {
        return new cfg.SeasonFrameConfig(_buf);
    }

    /// <summary>
    /// 赛季ID
    /// </summary>
    public readonly string SeasonId;
    /// <summary>
    /// 节点序号(1/2)
    /// </summary>
    public readonly int NodeIndex;
    /// <summary>
    /// 所需Frame Points
    /// </summary>
    public readonly int RequiredPoints;
    /// <summary>
    /// 头像框资源名
    /// </summary>
    public readonly string FrameAsset;
    /// <summary>
    /// 头像框名称
    /// </summary>
    public readonly string FrameName;
   
    public const int __ID__ = -596327166;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "seasonId:" + SeasonId + ","
        + "nodeIndex:" + NodeIndex + ","
        + "requiredPoints:" + RequiredPoints + ","
        + "frameAsset:" + FrameAsset + ","
        + "frameName:" + FrameName + ","
        + "}";
    }
}
}

