
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class ShareRewardConfig : Luban.BeanBase
{
    public ShareRewardConfig(ByteBuf _buf) 
    {
        Scene = _buf.ReadString();
        SharerRewardType = _buf.ReadString();
        SharerRewardAmount = _buf.ReadInt();
        ReceiverRewardType = _buf.ReadString();
        ReceiverRewardAmount = _buf.ReadInt();
    }

    public static ShareRewardConfig DeserializeShareRewardConfig(ByteBuf _buf)
    {
        return new cfg.ShareRewardConfig(_buf);
    }

    /// <summary>
    /// 分享场景
    /// </summary>
    public readonly string Scene;
    /// <summary>
    /// 分享者奖励类型
    /// </summary>
    public readonly string SharerRewardType;
    /// <summary>
    /// 分享者奖励数量
    /// </summary>
    public readonly int SharerRewardAmount;
    /// <summary>
    /// 被分享者奖励类型
    /// </summary>
    public readonly string ReceiverRewardType;
    /// <summary>
    /// 被分享者奖励数量
    /// </summary>
    public readonly int ReceiverRewardAmount;
   
    public const int __ID__ = 375438758;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "scene:" + Scene + ","
        + "sharerRewardType:" + SharerRewardType + ","
        + "sharerRewardAmount:" + SharerRewardAmount + ","
        + "receiverRewardType:" + ReceiverRewardType + ","
        + "receiverRewardAmount:" + ReceiverRewardAmount + ","
        + "}";
    }
}
}

