
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class StageConfig : Luban.BeanBase
{
    public StageConfig(ByteBuf _buf) 
    {
        StageId = _buf.ReadString();
        StageName = _buf.ReadString();
        SortOrder = _buf.ReadInt();
        StartPackId = _buf.ReadString();
        if(_buf.ReadBool()){ UnlockNextStage = _buf.ReadString(); } else { UnlockNextStage = null; }
    }

    public static StageConfig DeserializeStageConfig(ByteBuf _buf)
    {
        return new cfg.StageConfig(_buf);
    }

    /// <summary>
    /// 学段ID
    /// </summary>
    public readonly string StageId;
    /// <summary>
    /// 学段名称
    /// </summary>
    public readonly string StageName;
    /// <summary>
    /// 排序序号
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 起始关卡包ID
    /// </summary>
    public readonly string StartPackId;
    /// <summary>
    /// 完成后解锁的下一学段ID
    /// </summary>
    public readonly string UnlockNextStage;
   
    public const int __ID__ = 1598678326;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "stageId:" + StageId + ","
        + "stageName:" + StageName + ","
        + "sortOrder:" + SortOrder + ","
        + "startPackId:" + StartPackId + ","
        + "unlockNextStage:" + UnlockNextStage + ","
        + "}";
    }
}
}

