
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class StreakConfig : Luban.BeanBase
{
    public StreakConfig(ByteBuf _buf) 
    {
        StreakDays = _buf.ReadInt();
        RewardType = _buf.ReadString();
        if(_buf.ReadBool()){ RewardCoins = _buf.ReadInt(); } else { RewardCoins = null; }
        if(_buf.ReadBool()){ RewardItemId = _buf.ReadString(); } else { RewardItemId = null; }
        if(_buf.ReadBool()){ RewardItemCount = _buf.ReadInt(); } else { RewardItemCount = null; }
    }

    public static StreakConfig DeserializeStreakConfig(ByteBuf _buf)
    {
        return new cfg.StreakConfig(_buf);
    }

    /// <summary>
    /// 连续天数节点
    /// </summary>
    public readonly int StreakDays;
    /// <summary>
    /// 奖励类型(coins/item/combo)
    /// </summary>
    public readonly string RewardType;
    /// <summary>
    /// 奖励金币
    /// </summary>
    public readonly int? RewardCoins;
    /// <summary>
    /// 奖励道具ID
    /// </summary>
    public readonly string RewardItemId;
    /// <summary>
    /// 奖励道具数量
    /// </summary>
    public readonly int? RewardItemCount;
   
    public const int __ID__ = -205821494;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "streakDays:" + StreakDays + ","
        + "rewardType:" + RewardType + ","
        + "rewardCoins:" + RewardCoins + ","
        + "rewardItemId:" + RewardItemId + ","
        + "rewardItemCount:" + RewardItemCount + ","
        + "}";
    }
}
}

