
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 广告配置表
/// </summary>
public partial class TbAdConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.AdConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.AdConfig> _dataList;
    
    public TbAdConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.AdConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.AdConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.AdConfig _v;
            _v = global::GameConfig.cfg.AdConfig.DeserializeAdConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AdSlotId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.AdConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.AdConfig> DataList => _dataList;

    public cfg.AdConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.AdConfig Get(string key) => _dataMap[key];
    public cfg.AdConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

