
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 防沉迷配置表
/// </summary>
public partial class TbAntiAddictionConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.AntiAddictionConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.AntiAddictionConfig> _dataList;
    
    public TbAntiAddictionConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.AntiAddictionConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.AntiAddictionConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.AntiAddictionConfig _v;
            _v = global::GameConfig.cfg.AntiAddictionConfig.DeserializeAntiAddictionConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RuleId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.AntiAddictionConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.AntiAddictionConfig> DataList => _dataList;

    public cfg.AntiAddictionConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.AntiAddictionConfig Get(string key) => _dataMap[key];
    public cfg.AntiAddictionConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

