
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 头像活动配置表
/// </summary>
public partial class TbAvatarEventConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.AvatarEventConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.AvatarEventConfig> _dataList;
    
    public TbAvatarEventConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.AvatarEventConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.AvatarEventConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.AvatarEventConfig _v;
            _v = global::GameConfig.cfg.AvatarEventConfig.DeserializeAvatarEventConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AvatarEventId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.AvatarEventConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.AvatarEventConfig> DataList => _dataList;

    public cfg.AvatarEventConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.AvatarEventConfig Get(string key) => _dataMap[key];
    public cfg.AvatarEventConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

