
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 头像活动物品表
/// </summary>
public partial class TbAvatarEventItems
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.AvatarEventItem> _dataMap;
    private readonly System.Collections.Generic.List<cfg.AvatarEventItem> _dataList;
    
    public TbAvatarEventItems(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.AvatarEventItem>(n);
        _dataList = new System.Collections.Generic.List<cfg.AvatarEventItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.AvatarEventItem _v;
            _v = global::GameConfig.cfg.AvatarEventItem.DeserializeAvatarEventItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AvatarId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.AvatarEventItem> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.AvatarEventItem> DataList => _dataList;

    public cfg.AvatarEventItem GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.AvatarEventItem Get(string key) => _dataMap[key];
    public cfg.AvatarEventItem this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

