
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 称号徽章配置表
/// </summary>
public partial class TbBadgeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.BadgeConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.BadgeConfig> _dataList;
    
    public TbBadgeConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.BadgeConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.BadgeConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.BadgeConfig _v;
            _v = global::GameConfig.cfg.BadgeConfig.DeserializeBadgeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BadgeLevel, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.BadgeConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.BadgeConfig> DataList => _dataList;

    public cfg.BadgeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.BadgeConfig Get(int key) => _dataMap[key];
    public cfg.BadgeConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

