
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 金币规则表
/// </summary>
public partial class TbCoinRule
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.CoinRule> _dataMap;
    private readonly System.Collections.Generic.List<cfg.CoinRule> _dataList;
    
    public TbCoinRule(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.CoinRule>(n);
        _dataList = new System.Collections.Generic.List<cfg.CoinRule>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.CoinRule _v;
            _v = global::GameConfig.cfg.CoinRule.DeserializeCoinRule(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.RuleId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.CoinRule> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.CoinRule> DataList => _dataList;

    public cfg.CoinRule GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.CoinRule Get(string key) => _dataMap[key];
    public cfg.CoinRule this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

