
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 每日奖励配置表
/// </summary>
public partial class TbDailyRewardConfig
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.DailyRewardConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.DailyRewardConfig> _dataList;
    
    public TbDailyRewardConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.DailyRewardConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.DailyRewardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.DailyRewardConfig _v;
            _v = global::GameConfig.cfg.DailyRewardConfig.DeserializeDailyRewardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Day, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.DailyRewardConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.DailyRewardConfig> DataList => _dataList;

    public cfg.DailyRewardConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.DailyRewardConfig Get(int key) => _dataMap[key];
    public cfg.DailyRewardConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

