
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 每日冲刺配置表
/// </summary>
public partial class TbDailyDashConfig
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.DailyDashConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.DailyDashConfig> _dataList;
    
    public TbDailyDashConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.DailyDashConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.DailyDashConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.DailyDashConfig _v;
            _v = global::GameConfig.cfg.DailyDashConfig.DeserializeDailyDashConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.DayIndex, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.DailyDashConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.DailyDashConfig> DataList => _dataList;

    public cfg.DailyDashConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.DailyDashConfig Get(int key) => _dataMap[key];
    public cfg.DailyDashConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

