
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 每日挑战配置表
/// </summary>
public partial class TbDailyChallengeConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.DailyChallengeConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.DailyChallengeConfig> _dataList;
    
    public TbDailyChallengeConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.DailyChallengeConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.DailyChallengeConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.DailyChallengeConfig _v;
            _v = global::GameConfig.cfg.DailyChallengeConfig.DeserializeDailyChallengeConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ChallengeId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.DailyChallengeConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.DailyChallengeConfig> DataList => _dataList;

    public cfg.DailyChallengeConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.DailyChallengeConfig Get(string key) => _dataMap[key];
    public cfg.DailyChallengeConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

