
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 活动配置表
/// </summary>
public partial class TbEventConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.EventConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.EventConfig> _dataList;
    
    public TbEventConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.EventConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.EventConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.EventConfig _v;
            _v = global::GameConfig.cfg.EventConfig.DeserializeEventConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.EventId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.EventConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.EventConfig> DataList => _dataList;

    public cfg.EventConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.EventConfig Get(string key) => _dataMap[key];
    public cfg.EventConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

