
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 道具配置表
/// </summary>
public partial class TbItemConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.ItemConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.ItemConfig> _dataList;
    
    public TbItemConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.ItemConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.ItemConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.ItemConfig _v;
            _v = global::GameConfig.cfg.ItemConfig.DeserializeItemConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.ItemConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.ItemConfig> DataList => _dataList;

    public cfg.ItemConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.ItemConfig Get(string key) => _dataMap[key];
    public cfg.ItemConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

