
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 景区卡片配置表
/// </summary>
public partial class TbLandmarkCardConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.LandmarkCardConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.LandmarkCardConfig> _dataList;
    
    public TbLandmarkCardConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.LandmarkCardConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.LandmarkCardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.LandmarkCardConfig _v;
            _v = global::GameConfig.cfg.LandmarkCardConfig.DeserializeLandmarkCardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CardId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.LandmarkCardConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.LandmarkCardConfig> DataList => _dataList;

    public cfg.LandmarkCardConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.LandmarkCardConfig Get(string key) => _dataMap[key];
    public cfg.LandmarkCardConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

