
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 关卡包配置表
/// </summary>
public partial class TbPackConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.PackConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.PackConfig> _dataList;
    
    public TbPackConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.PackConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.PackConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.PackConfig _v;
            _v = global::GameConfig.cfg.PackConfig.DeserializePackConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.PackId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.PackConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.PackConfig> DataList => _dataList;

    public cfg.PackConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.PackConfig Get(string key) => _dataMap[key];
    public cfg.PackConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

