
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 省份里程碑配置表
/// </summary>
public partial class TbProvinceMilestoneConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.ProvinceMilestoneConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.ProvinceMilestoneConfig> _dataList;
    
    public TbProvinceMilestoneConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.ProvinceMilestoneConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.ProvinceMilestoneConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.ProvinceMilestoneConfig _v;
            _v = global::GameConfig.cfg.ProvinceMilestoneConfig.DeserializeProvinceMilestoneConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.MilestoneId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.ProvinceMilestoneConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.ProvinceMilestoneConfig> DataList => _dataList;

    public cfg.ProvinceMilestoneConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.ProvinceMilestoneConfig Get(string key) => _dataMap[key];
    public cfg.ProvinceMilestoneConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

