
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 赛季头像框节点表
/// </summary>
public partial class TbSeasonFrameConfig
{
    private readonly System.Collections.Generic.List<cfg.SeasonFrameConfig> _dataList;

    private System.Collections.Generic.Dictionary<(string, int), cfg.SeasonFrameConfig> _dataMapUnion;

    public TbSeasonFrameConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<cfg.SeasonFrameConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.SeasonFrameConfig _v;
            _v = global::GameConfig.cfg.SeasonFrameConfig.DeserializeSeasonFrameConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int), cfg.SeasonFrameConfig>(n);
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.SeasonId, _v.NodeIndex), _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<cfg.SeasonFrameConfig> DataList => _dataList;

    public cfg.SeasonFrameConfig Get(string season_id, int node_index) => _dataMapUnion.TryGetValue((season_id, node_index), out cfg.SeasonFrameConfig __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

