
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 赛季配置表
/// </summary>
public partial class TbSeasonConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.SeasonConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.SeasonConfig> _dataList;
    
    public TbSeasonConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.SeasonConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.SeasonConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.SeasonConfig _v;
            _v = global::GameConfig.cfg.SeasonConfig.DeserializeSeasonConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.SeasonId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.SeasonConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.SeasonConfig> DataList => _dataList;

    public cfg.SeasonConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.SeasonConfig Get(string key) => _dataMap[key];
    public cfg.SeasonConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

