
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 分享奖励配置表
/// </summary>
public partial class TbShareRewardConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.ShareRewardConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.ShareRewardConfig> _dataList;
    
    public TbShareRewardConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.ShareRewardConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.ShareRewardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.ShareRewardConfig _v;
            _v = global::GameConfig.cfg.ShareRewardConfig.DeserializeShareRewardConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Scene, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.ShareRewardConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.ShareRewardConfig> DataList => _dataList;

    public cfg.ShareRewardConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.ShareRewardConfig Get(string key) => _dataMap[key];
    public cfg.ShareRewardConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

