
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 连胜奖励配置表
/// </summary>
public partial class TbStreakConfig
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.StreakConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.StreakConfig> _dataList;
    
    public TbStreakConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.StreakConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.StreakConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.StreakConfig _v;
            _v = global::GameConfig.cfg.StreakConfig.DeserializeStreakConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.StreakDays, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.StreakConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.StreakConfig> DataList => _dataList;

    public cfg.StreakConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.StreakConfig Get(int key) => _dataMap[key];
    public cfg.StreakConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

