
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 学段配置表
/// </summary>
public partial class TbStageConfig
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.StageConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.StageConfig> _dataList;
    
    public TbStageConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.StageConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.StageConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.StageConfig _v;
            _v = global::GameConfig.cfg.StageConfig.DeserializeStageConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.StageId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.StageConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.StageConfig> DataList => _dataList;

    public cfg.StageConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.StageConfig Get(string key) => _dataMap[key];
    public cfg.StageConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

