
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 赛事奖励配置表
/// </summary>
public partial class TbTournamentRewardConfig
{
    private readonly System.Collections.Generic.List<cfg.TournamentRewardConfig> _dataList;

    private System.Collections.Generic.Dictionary<(string, int, int), cfg.TournamentRewardConfig> _dataMapUnion;

    public TbTournamentRewardConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<cfg.TournamentRewardConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.TournamentRewardConfig _v;
            _v = global::GameConfig.cfg.TournamentRewardConfig.DeserializeTournamentRewardConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(string, int, int), cfg.TournamentRewardConfig>(n);
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.TournamentType, _v.RankMin, _v.RankMax), _v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<cfg.TournamentRewardConfig> DataList => _dataList;

    public cfg.TournamentRewardConfig Get(string tournament_type, int rank_min, int rank_max) => _dataMapUnion.TryGetValue((tournament_type, rank_min, rank_max), out cfg.TournamentRewardConfig __v) ? __v : default;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

