
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 词王赛配置表
/// </summary>
public partial class TbWordMasterConfig
{
    private readonly System.Collections.Generic.Dictionary<int, cfg.WordMasterConfig> _dataMap;
    private readonly System.Collections.Generic.List<cfg.WordMasterConfig> _dataList;
    
    public TbWordMasterConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, cfg.WordMasterConfig>(n);
        _dataList = new System.Collections.Generic.List<cfg.WordMasterConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.WordMasterConfig _v;
            _v = global::GameConfig.cfg.WordMasterConfig.DeserializeWordMasterConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.NodeIndex, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, cfg.WordMasterConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.WordMasterConfig> DataList => _dataList;

    public cfg.WordMasterConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.WordMasterConfig Get(int key) => _dataMap[key];
    public cfg.WordMasterConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

