
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
/// <summary>
/// 单词总池表
/// </summary>
public partial class TbWordPool
{
    private readonly System.Collections.Generic.Dictionary<string, cfg.WordPool> _dataMap;
    private readonly System.Collections.Generic.List<cfg.WordPool> _dataList;
    
    public TbWordPool(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, cfg.WordPool>(n);
        _dataList = new System.Collections.Generic.List<cfg.WordPool>(n);
        for(int i = n ; i > 0 ; --i)
        {
            cfg.WordPool _v;
            _v = global::GameConfig.cfg.WordPool.DeserializeWordPool(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Word, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, cfg.WordPool> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<cfg.WordPool> DataList => _dataList;

    public cfg.WordPool GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public cfg.WordPool Get(string key) => _dataMap[key];
    public cfg.WordPool this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

