
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class TournamentRewardConfig : Luban.BeanBase
{
    public TournamentRewardConfig(ByteBuf _buf) 
    {
        TournamentType = _buf.ReadString();
        RankMin = _buf.ReadInt();
        RankMax = _buf.ReadInt();
        RewardCoins = _buf.ReadInt();
        RewardCrownPoints = _buf.ReadInt();
    }

    public static TournamentRewardConfig DeserializeTournamentRewardConfig(ByteBuf _buf)
    {
        return new cfg.TournamentRewardConfig(_buf);
    }

    /// <summary>
    /// 赛事类型(weekday/weekend)
    /// </summary>
    public readonly string TournamentType;
    /// <summary>
    /// 排名起始
    /// </summary>
    public readonly int RankMin;
    /// <summary>
    /// 排名结束
    /// </summary>
    public readonly int RankMax;
    /// <summary>
    /// 奖励金币
    /// </summary>
    public readonly int RewardCoins;
    /// <summary>
    /// 奖励皇冠积分
    /// </summary>
    public readonly int RewardCrownPoints;
   
    public const int __ID__ = 625933508;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "tournamentType:" + TournamentType + ","
        + "rankMin:" + RankMin + ","
        + "rankMax:" + RankMax + ","
        + "rewardCoins:" + RewardCoins + ","
        + "rewardCrownPoints:" + RewardCrownPoints + ","
        + "}";
    }
}
}

