
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class WordPool : Luban.BeanBase
{
    public WordPool(ByteBuf _buf) 
    {
        Word = _buf.ReadString();
        Translation = _buf.ReadString();
        Phonetic = _buf.ReadString();
        ExampleEn = _buf.ReadString();
        AudioFile = _buf.ReadString();
    }

    public static WordPool DeserializeWordPool(ByteBuf _buf)
    {
        return new cfg.WordPool(_buf);
    }

    /// <summary>
    /// 单词(大写)
    /// </summary>
    public readonly string Word;
    /// <summary>
    /// 中文释义
    /// </summary>
    public readonly string Translation;
    /// <summary>
    /// 音标
    /// </summary>
    public readonly string Phonetic;
    /// <summary>
    /// 英文例句
    /// </summary>
    public readonly string ExampleEn;
    /// <summary>
    /// 音频文件名
    /// </summary>
    public readonly string AudioFile;
   
    public const int __ID__ = 1077167280;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "word:" + Word + ","
        + "translation:" + Translation + ","
        + "phonetic:" + Phonetic + ","
        + "exampleEn:" + ExampleEn + ","
        + "audioFile:" + AudioFile + ","
        + "}";
    }
}
}

