
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.cfg
{
public sealed partial class WordMasterConfig : Luban.BeanBase
{
    public WordMasterConfig(ByteBuf _buf) 
    {
        NodeIndex = _buf.ReadInt();
        NodeType = _buf.ReadString();
        if(_buf.ReadBool()){ RewardCoins = _buf.ReadInt(); } else { RewardCoins = null; }
        if(_buf.ReadBool()){ RewardItemId = _buf.ReadString(); } else { RewardItemId = null; }
        if(_buf.ReadBool()){ RewardItemCount = _buf.ReadInt(); } else { RewardItemCount = null; }
        if(_buf.ReadBool()){ BuffType = _buf.ReadString(); } else { BuffType = null; }
        if(_buf.ReadBool()){ BuffDurationMin = _buf.ReadInt(); } else { BuffDurationMin = null; }
        RequiredWords = _buf.ReadInt();
        IsFinal = _buf.ReadBool();
    }

    public static WordMasterConfig DeserializeWordMasterConfig(ByteBuf _buf)
    {
        return new cfg.WordMasterConfig(_buf);
    }

    /// <summary>
    /// 节点序号
    /// </summary>
    public readonly int NodeIndex;
    /// <summary>
    /// 节点类型(coins/item/buff/combo)
    /// </summary>
    public readonly string NodeType;
    /// <summary>
    /// 奖励金币
    /// </summary>
    public readonly int? RewardCoins;
    /// <summary>
    /// 奖励道具ID
    /// </summary>
    public readonly string RewardItemId;
    /// <summary>
    /// 奖励道具数量
    /// </summary>
    public readonly int? RewardItemCount;
    /// <summary>
    /// Buff类型
    /// </summary>
    public readonly string BuffType;
    /// <summary>
    /// Buff持续分钟
    /// </summary>
    public readonly int? BuffDurationMin;
    /// <summary>
    /// 累计需找到的单词数
    /// </summary>
    public readonly int RequiredWords;
    /// <summary>
    /// 是否终极大奖
    /// </summary>
    public readonly bool IsFinal;
   
    public const int __ID__ = 594583768;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nodeIndex:" + NodeIndex + ","
        + "nodeType:" + NodeType + ","
        + "rewardCoins:" + RewardCoins + ","
        + "rewardItemId:" + RewardItemId + ","
        + "rewardItemCount:" + RewardItemCount + ","
        + "buffType:" + BuffType + ","
        + "buffDurationMin:" + BuffDurationMin + ","
        + "requiredWords:" + RequiredWords + ","
        + "isFinal:" + IsFinal + ","
        + "}";
    }
}
}

