
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    /// <summary>
    /// 学段配置表
    /// </summary>
    private cfg.TbStageConfig m_TbStageConfig;
    public cfg.TbStageConfig TbStageConfig 
    {
        get
        {
            if (m_TbStageConfig == null)
            {
                m_TbStageConfig = new cfg.TbStageConfig(defaultLoader("cfg_tbstageconfig"));
                m_TbStageConfig.ResolveRef(this);
            }
            return m_TbStageConfig;
        }
        set
        {
            m_TbStageConfig = value;
            m_TbStageConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 关卡包配置表
    /// </summary>
    private cfg.TbPackConfig m_TbPackConfig;
    public cfg.TbPackConfig TbPackConfig 
    {
        get
        {
            if (m_TbPackConfig == null)
            {
                m_TbPackConfig = new cfg.TbPackConfig(defaultLoader("cfg_tbpackconfig"));
                m_TbPackConfig.ResolveRef(this);
            }
            return m_TbPackConfig;
        }
        set
        {
            m_TbPackConfig = value;
            m_TbPackConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 单词总池表
    /// </summary>
    private cfg.TbWordPool m_TbWordPool;
    public cfg.TbWordPool TbWordPool 
    {
        get
        {
            if (m_TbWordPool == null)
            {
                m_TbWordPool = new cfg.TbWordPool(defaultLoader("cfg_tbwordpool"));
                m_TbWordPool.ResolveRef(this);
            }
            return m_TbWordPool;
        }
        set
        {
            m_TbWordPool = value;
            m_TbWordPool.ResolveRef(this);
        }
    }
    /// <summary>
    /// 道具配置表
    /// </summary>
    private cfg.TbItemConfig m_TbItemConfig;
    public cfg.TbItemConfig TbItemConfig 
    {
        get
        {
            if (m_TbItemConfig == null)
            {
                m_TbItemConfig = new cfg.TbItemConfig(defaultLoader("cfg_tbitemconfig"));
                m_TbItemConfig.ResolveRef(this);
            }
            return m_TbItemConfig;
        }
        set
        {
            m_TbItemConfig = value;
            m_TbItemConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 称号徽章配置表
    /// </summary>
    private cfg.TbBadgeConfig m_TbBadgeConfig;
    public cfg.TbBadgeConfig TbBadgeConfig 
    {
        get
        {
            if (m_TbBadgeConfig == null)
            {
                m_TbBadgeConfig = new cfg.TbBadgeConfig(defaultLoader("cfg_tbbadgeconfig"));
                m_TbBadgeConfig.ResolveRef(this);
            }
            return m_TbBadgeConfig;
        }
        set
        {
            m_TbBadgeConfig = value;
            m_TbBadgeConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 景区卡片配置表
    /// </summary>
    private cfg.TbLandmarkCardConfig m_TbLandmarkCardConfig;
    public cfg.TbLandmarkCardConfig TbLandmarkCardConfig 
    {
        get
        {
            if (m_TbLandmarkCardConfig == null)
            {
                m_TbLandmarkCardConfig = new cfg.TbLandmarkCardConfig(defaultLoader("cfg_tblandmarkcardconfig"));
                m_TbLandmarkCardConfig.ResolveRef(this);
            }
            return m_TbLandmarkCardConfig;
        }
        set
        {
            m_TbLandmarkCardConfig = value;
            m_TbLandmarkCardConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 金币规则表
    /// </summary>
    private cfg.TbCoinRule m_TbCoinRule;
    public cfg.TbCoinRule TbCoinRule 
    {
        get
        {
            if (m_TbCoinRule == null)
            {
                m_TbCoinRule = new cfg.TbCoinRule(defaultLoader("cfg_tbcoinrule"));
                m_TbCoinRule.ResolveRef(this);
            }
            return m_TbCoinRule;
        }
        set
        {
            m_TbCoinRule = value;
            m_TbCoinRule.ResolveRef(this);
        }
    }
    /// <summary>
    /// 防沉迷配置表
    /// </summary>
    private cfg.TbAntiAddictionConfig m_TbAntiAddictionConfig;
    public cfg.TbAntiAddictionConfig TbAntiAddictionConfig 
    {
        get
        {
            if (m_TbAntiAddictionConfig == null)
            {
                m_TbAntiAddictionConfig = new cfg.TbAntiAddictionConfig(defaultLoader("cfg_tbantiaddictionconfig"));
                m_TbAntiAddictionConfig.ResolveRef(this);
            }
            return m_TbAntiAddictionConfig;
        }
        set
        {
            m_TbAntiAddictionConfig = value;
            m_TbAntiAddictionConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 广告配置表
    /// </summary>
    private cfg.TbAdConfig m_TbAdConfig;
    public cfg.TbAdConfig TbAdConfig 
    {
        get
        {
            if (m_TbAdConfig == null)
            {
                m_TbAdConfig = new cfg.TbAdConfig(defaultLoader("cfg_tbadconfig"));
                m_TbAdConfig.ResolveRef(this);
            }
            return m_TbAdConfig;
        }
        set
        {
            m_TbAdConfig = value;
            m_TbAdConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 头像活动配置表
    /// </summary>
    private cfg.TbAvatarEventConfig m_TbAvatarEventConfig;
    public cfg.TbAvatarEventConfig TbAvatarEventConfig 
    {
        get
        {
            if (m_TbAvatarEventConfig == null)
            {
                m_TbAvatarEventConfig = new cfg.TbAvatarEventConfig(defaultLoader("cfg_tbavatareventconfig"));
                m_TbAvatarEventConfig.ResolveRef(this);
            }
            return m_TbAvatarEventConfig;
        }
        set
        {
            m_TbAvatarEventConfig = value;
            m_TbAvatarEventConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 头像活动物品表
    /// </summary>
    private cfg.TbAvatarEventItems m_TbAvatarEventItems;
    public cfg.TbAvatarEventItems TbAvatarEventItems 
    {
        get
        {
            if (m_TbAvatarEventItems == null)
            {
                m_TbAvatarEventItems = new cfg.TbAvatarEventItems(defaultLoader("cfg_tbavatareventitems"));
                m_TbAvatarEventItems.ResolveRef(this);
            }
            return m_TbAvatarEventItems;
        }
        set
        {
            m_TbAvatarEventItems = value;
            m_TbAvatarEventItems.ResolveRef(this);
        }
    }
    /// <summary>
    /// 每日挑战配置表
    /// </summary>
    private cfg.TbDailyChallengeConfig m_TbDailyChallengeConfig;
    public cfg.TbDailyChallengeConfig TbDailyChallengeConfig 
    {
        get
        {
            if (m_TbDailyChallengeConfig == null)
            {
                m_TbDailyChallengeConfig = new cfg.TbDailyChallengeConfig(defaultLoader("cfg_tbdailychallengeconfig"));
                m_TbDailyChallengeConfig.ResolveRef(this);
            }
            return m_TbDailyChallengeConfig;
        }
        set
        {
            m_TbDailyChallengeConfig = value;
            m_TbDailyChallengeConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 每日冲刺配置表
    /// </summary>
    private cfg.TbDailyDashConfig m_TbDailyDashConfig;
    public cfg.TbDailyDashConfig TbDailyDashConfig 
    {
        get
        {
            if (m_TbDailyDashConfig == null)
            {
                m_TbDailyDashConfig = new cfg.TbDailyDashConfig(defaultLoader("cfg_tbdailydashconfig"));
                m_TbDailyDashConfig.ResolveRef(this);
            }
            return m_TbDailyDashConfig;
        }
        set
        {
            m_TbDailyDashConfig = value;
            m_TbDailyDashConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 每日奖励配置表
    /// </summary>
    private cfg.TbDailyRewardConfig m_TbDailyRewardConfig;
    public cfg.TbDailyRewardConfig TbDailyRewardConfig 
    {
        get
        {
            if (m_TbDailyRewardConfig == null)
            {
                m_TbDailyRewardConfig = new cfg.TbDailyRewardConfig(defaultLoader("cfg_tbdailyrewardconfig"));
                m_TbDailyRewardConfig.ResolveRef(this);
            }
            return m_TbDailyRewardConfig;
        }
        set
        {
            m_TbDailyRewardConfig = value;
            m_TbDailyRewardConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 活动配置表
    /// </summary>
    private cfg.TbEventConfig m_TbEventConfig;
    public cfg.TbEventConfig TbEventConfig 
    {
        get
        {
            if (m_TbEventConfig == null)
            {
                m_TbEventConfig = new cfg.TbEventConfig(defaultLoader("cfg_tbeventconfig"));
                m_TbEventConfig.ResolveRef(this);
            }
            return m_TbEventConfig;
        }
        set
        {
            m_TbEventConfig = value;
            m_TbEventConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 省份里程碑配置表
    /// </summary>
    private cfg.TbProvinceMilestoneConfig m_TbProvinceMilestoneConfig;
    public cfg.TbProvinceMilestoneConfig TbProvinceMilestoneConfig 
    {
        get
        {
            if (m_TbProvinceMilestoneConfig == null)
            {
                m_TbProvinceMilestoneConfig = new cfg.TbProvinceMilestoneConfig(defaultLoader("cfg_tbprovincemilestoneconfig"));
                m_TbProvinceMilestoneConfig.ResolveRef(this);
            }
            return m_TbProvinceMilestoneConfig;
        }
        set
        {
            m_TbProvinceMilestoneConfig = value;
            m_TbProvinceMilestoneConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 赛季配置表
    /// </summary>
    private cfg.TbSeasonConfig m_TbSeasonConfig;
    public cfg.TbSeasonConfig TbSeasonConfig 
    {
        get
        {
            if (m_TbSeasonConfig == null)
            {
                m_TbSeasonConfig = new cfg.TbSeasonConfig(defaultLoader("cfg_tbseasonconfig"));
                m_TbSeasonConfig.ResolveRef(this);
            }
            return m_TbSeasonConfig;
        }
        set
        {
            m_TbSeasonConfig = value;
            m_TbSeasonConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 赛季皇冠节点表
    /// </summary>
    private cfg.TbSeasonCrownConfig m_TbSeasonCrownConfig;
    public cfg.TbSeasonCrownConfig TbSeasonCrownConfig 
    {
        get
        {
            if (m_TbSeasonCrownConfig == null)
            {
                m_TbSeasonCrownConfig = new cfg.TbSeasonCrownConfig(defaultLoader("cfg_tbseasoncrownconfig"));
                m_TbSeasonCrownConfig.ResolveRef(this);
            }
            return m_TbSeasonCrownConfig;
        }
        set
        {
            m_TbSeasonCrownConfig = value;
            m_TbSeasonCrownConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 赛季头像框节点表
    /// </summary>
    private cfg.TbSeasonFrameConfig m_TbSeasonFrameConfig;
    public cfg.TbSeasonFrameConfig TbSeasonFrameConfig 
    {
        get
        {
            if (m_TbSeasonFrameConfig == null)
            {
                m_TbSeasonFrameConfig = new cfg.TbSeasonFrameConfig(defaultLoader("cfg_tbseasonframeconfig"));
                m_TbSeasonFrameConfig.ResolveRef(this);
            }
            return m_TbSeasonFrameConfig;
        }
        set
        {
            m_TbSeasonFrameConfig = value;
            m_TbSeasonFrameConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 分享奖励配置表
    /// </summary>
    private cfg.TbShareRewardConfig m_TbShareRewardConfig;
    public cfg.TbShareRewardConfig TbShareRewardConfig 
    {
        get
        {
            if (m_TbShareRewardConfig == null)
            {
                m_TbShareRewardConfig = new cfg.TbShareRewardConfig(defaultLoader("cfg_tbsharerewardconfig"));
                m_TbShareRewardConfig.ResolveRef(this);
            }
            return m_TbShareRewardConfig;
        }
        set
        {
            m_TbShareRewardConfig = value;
            m_TbShareRewardConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 连胜奖励配置表
    /// </summary>
    private cfg.TbStreakConfig m_TbStreakConfig;
    public cfg.TbStreakConfig TbStreakConfig 
    {
        get
        {
            if (m_TbStreakConfig == null)
            {
                m_TbStreakConfig = new cfg.TbStreakConfig(defaultLoader("cfg_tbstreakconfig"));
                m_TbStreakConfig.ResolveRef(this);
            }
            return m_TbStreakConfig;
        }
        set
        {
            m_TbStreakConfig = value;
            m_TbStreakConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 赛事奖励配置表
    /// </summary>
    private cfg.TbTournamentRewardConfig m_TbTournamentRewardConfig;
    public cfg.TbTournamentRewardConfig TbTournamentRewardConfig 
    {
        get
        {
            if (m_TbTournamentRewardConfig == null)
            {
                m_TbTournamentRewardConfig = new cfg.TbTournamentRewardConfig(defaultLoader("cfg_tbtournamentrewardconfig"));
                m_TbTournamentRewardConfig.ResolveRef(this);
            }
            return m_TbTournamentRewardConfig;
        }
        set
        {
            m_TbTournamentRewardConfig = value;
            m_TbTournamentRewardConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 词王赛配置表
    /// </summary>
    private cfg.TbWordMasterConfig m_TbWordMasterConfig;
    public cfg.TbWordMasterConfig TbWordMasterConfig 
    {
        get
        {
            if (m_TbWordMasterConfig == null)
            {
                m_TbWordMasterConfig = new cfg.TbWordMasterConfig(defaultLoader("cfg_tbwordmasterconfig"));
                m_TbWordMasterConfig.ResolveRef(this);
            }
            return m_TbWordMasterConfig;
        }
        set
        {
            m_TbWordMasterConfig = value;
            m_TbWordMasterConfig.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
